apiVersion: v1
kind: ConfigMap
metadata:
  name: yarn-conf
data:
  yarn-site.xml: |
    <?xml version="1.0"?>
    <configuration>

    <!-- Site specific YARN configuration properties -->
     <property>
        <name>yarn.resourcemanager.webapp.address</name>
        <value>hadoop-hadoop-yarn-rm.default.svc.cluster.local:8088</value>
     </property>
     <property>
        <name>yarn.resourcemanager.webapp.https.address</name>
        <value>hadoop-hadoop-yarn-rm.default.svc.cluster.local:8090</value>
     </property>
     <property>
        <name>yarn.resourcemanager.resource-tracker.address</name>
        <value>hadoop-hadoop-yarn-rm.default.svc.cluster.local:8031</value>
     </property>

    </configuration>
